project:
  type: website
  output-dir: "."

website:
  title: |
    <span style="text-transform: none;">
    <span style="font-size: 1rem;">the</span><span style="font-size: 0.7rem;">&nbsp;</span>ABC<span style="font-size: 0.7rem;">&nbsp;</span>lab</span>
  search: false
  body-footer: |
  
    <div style="font-size: 0.8rem; margin-top: 5rem; border-top: 1px solid lightgrey; 
    border-bottom: 1px solid lightgrey; line-height: 0.95rem; padding: 0.5rem;">
    The ABC Lab is a collective project of 
    [Dr. Paul Galpern](pgalpern.qmd), 
    [Dr. Mindi Summers](msummers.qmd), 
    and their students and trainees at University of Calgary, Alberta, Canada.  
    <div style="font-size: 0.6rem; margin-top: 0.5rem; line-height: 0.7rem;">Image content 
    created by  past or present lab members is credited; other images are licensed or are in 
    the public domain;  Lab logo and beetle line drawing by Tobyn Neame; Built with Quarto; 
    Last content update:  May 2024</div></div>
  navbar:
    logo: /images/abclab.png
    #background: info
    background: "#f2f2f2"
    right:
      - text: "Projects"
        menu:
          - text: "Agriculture"
            file: projects_agriculture.qmd
          - text: "Biodiversity"
            file: projects_biodiversity.qmd
          - text: "Conservation"
            file: projects_conservation.qmd
      - text: "Products"
        menu: 
          - text: "Publications"
            file: publications.qmd
          - text: "Media"
            file: media.qmd
          - text: "Illustration"
            file: illustration.qmd
      - text: "People"
        menu:
          - text: "Students & Trainees"
            file: people2.qmd
          - text: "Dr. Paul Galpern"
            file: pgalpern.qmd
          - text: "Dr. Mindi Summers"
            file: msummers.qmd

      - text: "Join us"
        file: joinus.qmd
    collapse: TRUE
    collapse-below: xl
    pinned: TRUE
    

    

format:
  html:
    anchor-sections: false
    theme:
      - lux
      - custom.scss
    css: styles.css
    toc: false
    page-layout: full
    grid:
    #  sidebar-width: 0px
       body-width: 600px
       margin-width: 300px
    #  gutter-width: 1.5rem


editor: visual
execute:
  enabled: true


